service:
  name: switcher
  host: "0.0.0.0"
  port: 8080
discovery:
  keyPrefix: "/services/%s/"
  keyFormat: "/services/%s/%s"
  type: etcd
  etcd:
    endpoints:
      - "localhost:2379"
    dialTimeout: 5s
    leaseTTL: 10