// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.6.1
// source: protobuf/client-switch.client-switch

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RSAKeyExchange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *RSAKeyExchange) Reset() {
	*x = RSAKeyExchange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_client_switch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RSAKeyExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSAKeyExchange) ProtoMessage() {}

func (x *RSAKeyExchange) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_client_switch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSAKeyExchange.ProtoReflect.Descriptor instead.
func (*RSAKeyExchange) Descriptor() ([]byte, []int) {
	return file_protobuf_client_switch_proto_rawDescGZIP(), []int{0}
}

func (x *RSAKeyExchange) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type KeyExchange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *KeyExchange) Reset() {
	*x = KeyExchange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_client_switch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyExchange) ProtoMessage() {}

func (x *KeyExchange) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_client_switch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyExchange.ProtoReflect.Descriptor instead.
func (*KeyExchange) Descriptor() ([]byte, []int) {
	return file_protobuf_client_switch_proto_rawDescGZIP(), []int{1}
}

func (x *KeyExchange) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_protobuf_client_switch_proto protoreflect.FileDescriptor

var file_protobuf_client_switch_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2d, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x22, 0x0a, 0x0e, 0x52, 0x53, 0x41, 0x4b,
	0x65, 0x79, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x1f, 0x0a, 0x0b,
	0x4b, 0x65, 0x79, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x42, 0x0b, 0x5a,
	0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protobuf_client_switch_proto_rawDescOnce sync.Once
	file_protobuf_client_switch_proto_rawDescData = file_protobuf_client_switch_proto_rawDesc
)

func file_protobuf_client_switch_proto_rawDescGZIP() []byte {
	file_protobuf_client_switch_proto_rawDescOnce.Do(func() {
		file_protobuf_client_switch_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_client_switch_proto_rawDescData)
	})
	return file_protobuf_client_switch_proto_rawDescData
}

var file_protobuf_client_switch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_client_switch_proto_goTypes = []interface{}{
	(*RSAKeyExchange)(nil), // 0: protobuf.RSAKeyExchange
	(*KeyExchange)(nil),    // 1: protobuf.KeyExchange
}
var file_protobuf_client_switch_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_client_switch_proto_init() }
func file_protobuf_client_switch_proto_init() {
	if File_protobuf_client_switch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_client_switch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RSAKeyExchange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_client_switch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyExchange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_client_switch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_client_switch_proto_goTypes,
		DependencyIndexes: file_protobuf_client_switch_proto_depIdxs,
		MessageInfos:      file_protobuf_client_switch_proto_msgTypes,
	}.Build()
	File_protobuf_client_switch_proto = out.File
	file_protobuf_client_switch_proto_rawDesc = nil
	file_protobuf_client_switch_proto_goTypes = nil
	file_protobuf_client_switch_proto_depIdxs = nil
}
