// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.6.1
// source: protobuf/providee-switch.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dispatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientSid int32  `protobuf:"varint,1,opt,name=clientSid,proto3" json:"clientSid,omitempty"`
	TypeId    int32  `protobuf:"varint,2,opt,name=typeId,proto3" json:"typeId,omitempty"`
	PvId      int32  `protobuf:"varint,3,opt,name=pvId,proto3" json:"pvId,omitempty"`
	MsgData   []byte `protobuf:"bytes,4,opt,name=msgData,proto3" json:"msgData,omitempty"`
}

func (x *Dispatch) Reset() {
	*x = Dispatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_providee_switch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dispatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dispatch) ProtoMessage() {}

func (x *Dispatch) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_providee_switch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dispatch.ProtoReflect.Descriptor instead.
func (*Dispatch) Descriptor() ([]byte, []int) {
	return file_protobuf_providee_switch_proto_rawDescGZIP(), []int{0}
}

func (x *Dispatch) GetClientSid() int32 {
	if x != nil {
		return x.ClientSid
	}
	return 0
}

func (x *Dispatch) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *Dispatch) GetPvId() int32 {
	if x != nil {
		return x.PvId
	}
	return 0
}

func (x *Dispatch) GetMsgData() []byte {
	if x != nil {
		return x.MsgData
	}
	return nil
}

type ProvideeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PvId       int32    `protobuf:"varint,1,opt,name=pvId,proto3" json:"pvId,omitempty"`
	ServerType int32    `protobuf:"varint,2,opt,name=serverType,proto3" json:"serverType,omitempty"`
	ServerId   int32    `protobuf:"varint,3,opt,name=serverId,proto3" json:"serverId,omitempty"`
	Topics     []string `protobuf:"bytes,4,rep,name=topics,proto3" json:"topics,omitempty"`
	Ip         int32    `protobuf:"varint,5,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *ProvideeInfo) Reset() {
	*x = ProvideeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_providee_switch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvideeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvideeInfo) ProtoMessage() {}

func (x *ProvideeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_providee_switch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvideeInfo.ProtoReflect.Descriptor instead.
func (*ProvideeInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_providee_switch_proto_rawDescGZIP(), []int{1}
}

func (x *ProvideeInfo) GetPvId() int32 {
	if x != nil {
		return x.PvId
	}
	return 0
}

func (x *ProvideeInfo) GetServerType() int32 {
	if x != nil {
		return x.ServerType
	}
	return 0
}

func (x *ProvideeInfo) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ProvideeInfo) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *ProvideeInfo) GetIp() int32 {
	if x != nil {
		return x.Ip
	}
	return 0
}

var File_protobuf_providee_switch_proto protoreflect.FileDescriptor

var file_protobuf_providee_switch_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x65, 0x2d, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x6e, 0x0a, 0x08, 0x44, 0x69,
	0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x53, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x53, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x79, 0x70, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x76, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x76, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x22, 0x86, 0x01, 0x0a, 0x0c, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x76, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x76, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x70, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_providee_switch_proto_rawDescOnce sync.Once
	file_protobuf_providee_switch_proto_rawDescData = file_protobuf_providee_switch_proto_rawDesc
)

func file_protobuf_providee_switch_proto_rawDescGZIP() []byte {
	file_protobuf_providee_switch_proto_rawDescOnce.Do(func() {
		file_protobuf_providee_switch_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_providee_switch_proto_rawDescData)
	})
	return file_protobuf_providee_switch_proto_rawDescData
}

var file_protobuf_providee_switch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_providee_switch_proto_goTypes = []interface{}{
	(*Dispatch)(nil),     // 0: protobuf.Dispatch
	(*ProvideeInfo)(nil), // 1: protobuf.ProvideeInfo
}
var file_protobuf_providee_switch_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_providee_switch_proto_init() }
func file_protobuf_providee_switch_proto_init() {
	if File_protobuf_providee_switch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_providee_switch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dispatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_providee_switch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProvideeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_providee_switch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_providee_switch_proto_goTypes,
		DependencyIndexes: file_protobuf_providee_switch_proto_depIdxs,
		MessageInfos:      file_protobuf_providee_switch_proto_msgTypes,
	}.Build()
	File_protobuf_providee_switch_proto = out.File
	file_protobuf_providee_switch_proto_rawDesc = nil
	file_protobuf_providee_switch_proto_goTypes = nil
	file_protobuf_providee_switch_proto_depIdxs = nil
}
